credentials:
  usernames:
    test:
      email: test@test.com
      name: test
      password: abc
cookie:
  expiry_days: 0
  key: random_key
  name: random_cookie_name
preauthorized:
  emails:
  - blabla