[client]
showSidebarNavigation=false

[theme]
primaryColor="#faa613"
backgroundColor="#f5f5f5"
secondaryBackgroundColor="#dcdcdc"
textColor="#262730"
font="sans serif"

[server]
enableStaticServing = true
